import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Map;

/**
 * Generates {@code UnicodeCategoryData.java}, the Unicode general categories that I-Regexp's {@code \p{..}}
 * escapes use, from one fixed version of the Unicode Character Database, so that matching does not depend on
 * the Unicode version of the JDK (issue #24).
 *
 * <pre>
 * curl -LO https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
 * java scripts/GenerateUnicodeCategories.java 16.0.0 UnicodeData.txt \
 *     jsonpath-core/src/main/java/io/github/treetrail/jsonpath/internal/UnicodeCategoryData.java
 * </pre>
 *
 * <p>Each run of code points with the same category is encoded in five characters of the Base64 alphabet:
 * four for the first code point and one for the category, as a {@link Character#getType(int)} constant.
 */
public final class GenerateUnicodeCategories {

    private static final String ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    private static final Map<String, Byte> TYPES = Map.ofEntries(
            Map.entry("Lu", Character.UPPERCASE_LETTER),
            Map.entry("Ll", Character.LOWERCASE_LETTER),
            Map.entry("Lt", Character.TITLECASE_LETTER),
            Map.entry("Lm", Character.MODIFIER_LETTER),
            Map.entry("Lo", Character.OTHER_LETTER),
            Map.entry("Mn", Character.NON_SPACING_MARK),
            Map.entry("Me", Character.ENCLOSING_MARK),
            Map.entry("Mc", Character.COMBINING_SPACING_MARK),
            Map.entry("Nd", Character.DECIMAL_DIGIT_NUMBER),
            Map.entry("Nl", Character.LETTER_NUMBER),
            Map.entry("No", Character.OTHER_NUMBER),
            Map.entry("Zs", Character.SPACE_SEPARATOR),
            Map.entry("Zl", Character.LINE_SEPARATOR),
            Map.entry("Zp", Character.PARAGRAPH_SEPARATOR),
            Map.entry("Cc", Character.CONTROL),
            Map.entry("Cf", Character.FORMAT),
            Map.entry("Co", Character.PRIVATE_USE),
            Map.entry("Cs", Character.SURROGATE),
            Map.entry("Pd", Character.DASH_PUNCTUATION),
            Map.entry("Ps", Character.START_PUNCTUATION),
            Map.entry("Pe", Character.END_PUNCTUATION),
            Map.entry("Pc", Character.CONNECTOR_PUNCTUATION),
            Map.entry("Po", Character.OTHER_PUNCTUATION),
            Map.entry("Sm", Character.MATH_SYMBOL),
            Map.entry("Sc", Character.CURRENCY_SYMBOL),
            Map.entry("Sk", Character.MODIFIER_SYMBOL),
            Map.entry("So", Character.OTHER_SYMBOL),
            Map.entry("Pi", Character.INITIAL_QUOTE_PUNCTUATION),
            Map.entry("Pf", Character.FINAL_QUOTE_PUNCTUATION));

    public static void main(String[] args) throws IOException {
        if (args.length != 3) {
            System.err.println("usage: GenerateUnicodeCategories <version> <UnicodeData.txt> <output .java>");
            System.exit(2);
        }
        String version = args[0];
        byte[] types = new byte[Character.MAX_CODE_POINT + 1];
        Arrays.fill(types, Character.UNASSIGNED);
        int rangeStart = -1;
        for (String line : Files.readAllLines(Path.of(args[1]), StandardCharsets.UTF_8)) {
            String[] fields = line.split(";", -1);
            int cp = Integer.parseInt(fields[0], 16);
            Byte type = TYPES.get(fields[2]);
            if (type == null) {
                throw new IllegalArgumentException("Unknown category in: " + line);
            }
            if (fields[1].endsWith(", First>")) {
                rangeStart = cp;
            } else if (fields[1].endsWith(", Last>")) {
                Arrays.fill(types, rangeStart, cp + 1, type);
                rangeStart = -1;
            } else {
                types[cp] = type;
            }
        }

        StringBuilder data = new StringBuilder();
        int runs = 0;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            if (cp == 0 || types[cp] != types[cp - 1]) {
                for (int shift = 18; shift >= 0; shift -= 6) {
                    data.append(ALPHABET.charAt((cp >>> shift) & 63));
                }
                data.append(ALPHABET.charAt(types[cp]));
                runs++;
            }
        }

        StringBuilder source = new StringBuilder();
        source.append("package io.github.treetrail.jsonpath.internal;\n\n")
                .append("/**\n")
                .append(" * The Unicode general categories of Unicode ")
                .append(version)
                .append(", generated by {@code scripts/GenerateUnicodeCategories.java}\n")
                .append(" * from the Unicode Character Database (Unicode License V3, see META-INF/UNICODE-LICENSE.txt);\n")
                .append(" * do not edit. ")
                .append(runs)
                .append(" runs of code points, five characters each, see {@link UnicodeCategories}.\n")
                .append(" */\n")
                .append("final class UnicodeCategoryData {\n\n")
                .append("    static final String VERSION = \"")
                .append(version)
                .append("\";\n\n")
                .append("    static final int RUNS = ")
                .append(runs)
                .append(";\n\n")
                .append("    static final String RUN_DATA = \"\"");
        int lineLength = 90;
        for (int i = 0; i < data.length(); i += lineLength) {
            source.append("\n            + \"")
                    .append(data, i, Math.min(data.length(), i + lineLength))
                    .append('"');
        }
        source.append(";\n\n    private UnicodeCategoryData() {}\n}\n");
        Files.writeString(Path.of(args[2]), source.toString(), StandardCharsets.UTF_8);
        System.out.println(runs + " runs written to " + args[2]);
    }

    private GenerateUnicodeCategories() {}
}
